# Generated by Django 4.2.3 on 2023-07-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='symbol',
            field=models.CharField(default='', max_length=10),
        ),
    ]
